Add python3-setuptools as a run-time dependency so --version works
Fixes: https://github.com/rdiff-backup/rdiff-backup/issues/305

Also extend autopkgtest to verify this.

diff --git a/debian/tests/smoke b/debian/tests/smoke
--- a/debian/tests/smoke
+++ b/debian/tests/smoke
@@ -9,4 +9,18 @@ set -ex
 #   Fatal Error: No arguments given
 #   See the rdiff-backup manual page for more information.
 
-rdiff-backup --print-statistics 2>&1 | grep 'No arguments given'
+if rdiff-backup --print-statistics 2>&1 | grep -q 'No arguments given'
+then
+  echo "Basic smoke test passed"
+else
+  echo "Error: Basic smoke test failed, rdiff-backup might not even run"
+  exit 1
+fi
+
+if rdiff-backup --version | grep -q 'DEV'
+then
+  echo "Error: Version is 'DEV'"
+  exit 1
+else
+  echo "Version test passed"
+fi
